import genanki

# Define a unique model ID (randomly generated) for the Anki cards
my_model_id = 1627392319

my_model = genanki.Model(
  my_model_id,
  'Simple Model',
  fields=[
    {'name': 'Question'},
    {'name': 'Answer'},
  ],
  templates=[
    {
      'name': 'Card 1',
      'qfmt': '{{Question}}',
      'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}',
    },
  ],
  css="""
  .card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
  }
  """
)

# List of vocabulary pairs (French, English)
vocab_list = [
    ('the world / international stage', 'la scène internationale'),
    ('a sovereign state', 'un État souverain'),
    ('sovereignty', 'la souveraineté'),
    ('international law', 'le droit international'),
    ('foreign affairs', 'les affaires étrangères'),
    ('a global issue', 'un problème mondial'),
    ('geopolitics', 'la géopolitique'),
    ('western / eastern', 'occidental / oriental'),
    ('a border, a frontier', 'une frontière'),
    ('a diplomat', 'un diplomate'),
    ('diplomacy', 'la diplomatie'),
    ('break off/ resume diplomatic relations', 'rompre/reprendre les relations'),
    ('tense, strained relations', 'des relations tendues'),
    ('a thaw', 'un réchauffement'),
    ('a chill, a cooling off', 'un refroidissement'),
    ('imperialistic (adj)', 'impérialiste'),
    ('balance of power', "l'équilibre des force"),
    ('hegemony', "l'hégémonie"),
    ('the UN', "l'ONU"),
    ('to implement/enforce a resolution', 'appliquer une résolution'),
    ('an embargo', 'un embargo'),
    ('a peace-keeping operation', '...maintien de la paix'),
    ('a blue helmet', 'un casque bleu'),
    ('the duty to intervene', "le devoir d'ingérence"),
    ('to apply to join / for membership of', 'demander son adhésion à'),
    ('to negotiate', 'négocier'),
    ('talks', 'pourparlers'),
    ('to make /issue a statement', 'faire une déclaration'),
    ('a communiqué', 'un communiqué'),
    ('a summit / (meeting)', 'une réunion au sommet'),
    ('a spokesperson', 'un porte-parole'),
    ('a counterpart', 'un homologue'),
    ('a stalemate, a deadlock, a stand-off', 'une impasse'),
    ('to broker an agreement', 'négocier un accord'),
    ('to compromise', 'transiger'),
    ('ratify a treaty', 'ratifier un traité'),
    ('an NGO / a non-governmental organization', 'une ONG'),
    ('human rights', "les droits de l'homme"),
    ('reach a settlement', 'conclure un accord'),
    ('veto / a decision', 'mettre son véto à ...'),
    ('under the aegis of', "sous l'égide de"),
    ('a superpower', 'une superpuissance'),
    ('to uphold a principle', 'faire respecter un principe'),
    ('decolonization', 'la décolonisation'),
    ('to gain, achieve, attain independence', "obtenir l'indépendance"),
    ('a former colony', 'une ancienne colonie'),
    ('a colonial power', 'une puissance coloniale'),
    ('an armed conflict', 'un conflit armé'),
    ('military / civilian', 'militaire / civil'),
    ('enemy', 'ennemi'),
    ('warmongering', 'la propagande belliciste'),
    ('to be at war / peace', 'être en guerre / en paix'),
    ('to wage war on / against', 'faire la guerre à'),
    ('an ally', 'un allié'),
    ('to conquer', 'conquérir'),
    ('conquest', 'la conquête'),
    ('to invade', 'envahir'),
    ('troops', 'les troupes'),
    ('a soldier', 'un soldat'),
    ('a serviceman / woman', 'un.e militaire'),
    ('to join, to enlist', "s'engager, s'enrôler"),
    ('withdrawal', 'le retrait'),
    ('to retaliate against', 'user de représailles envers'),
    ('to defeat an adversary', 'vaincre un adversaire'),
    ('a prisoner of war / POW', 'un prisonnier de guerre'),
    ('NATO', "l'OTAN"),
    ('the wounded', 'les blessés'),
    ('the casualties', 'les morts et les blessés'),
    ('a genocide', 'un génocide'),
    ('ethnic cleansing', 'purification ethnique')
]

vocab_list2 = [
    ('a farmer', 'un fermier'),
    ('farming', "l'agriculture"),
    ('a stockbreeder', 'un éleveur'),
    ('a wheat farmer', 'un céréalier'),
    ('a market gardener', 'un maraîcher'),
    ('a beekeeper', 'un apiculteur'),
    ('a wine grower', 'un vigneron'),
    ('an agricultural engineer', 'un ingénieur agronome'),
    ('an estate', 'un domaine'),
    ('the top soil', 'la terre arable'),
    ('a crop, a harvest', 'une récolte'),
    ('land', 'de la terre'),
    ('a field', 'un champ'),
    ('a fence', 'une clôture'),
    ('a hedge', 'une haie'),
    ('a meadow', 'une prairie'),
    ('sustainable agriculture', "l'agriculture durable"),
    ('organic farming', "l'agriculture bio"),
    ('factory farming', "l'élevage industriel"),
    ('the CAP: Common Agricultural Policy', 'la Politique agricole commune (la PAC)'),
    ('GMOs', 'les OGM'),
    ('a biotech product', 'un produit transgénique'),
    ('crops', 'les récoltes'),
    ('crop subsidies', 'les subventions agricoles'),
    ('fertilizers', 'les engrais'),
    ('biofuels', 'les biocarburants'),
    ('free-range', 'élevé en plein air'),
    ('foot-and-mouth disease', 'la fièvre aphteuse'),
    ('mad cow disease', 'la maladie de la vache folle'),
    ('renewable', 'renouvelable'),
    ('ripe', 'mûr'),
    ('to cultivate (a field)', 'cultiver'),
    ('to grow', 'faire pousser'),
    ('to fertilize', 'amender (le sol)'),
    ('to irrigate', 'irriguer'),
    ('to water', 'arroser'),
    ('to plough', 'labourer'),
    ('to sow', 'semer'),
    ('to yield', 'produire'),
    ('to reap', 'moissonner'),
    ('to pick', 'cueillir'),
    ('to harvest / to reap', 'récolter'),
    ('to breed / to rear', "faire de l'élevage"),
    ('to subsidize', 'subventionner'),
    ('to ban', 'interdire'),
    ('the environment', "l'environnement"),
    ('environmental', 'écologique, lié à ...'),
    ('nature', 'la nature'),
    ('nature conservation', 'la protection de la nature'),
    ('wildlife', 'la faune et la flore'),
    ('a conservationist', 'un défenseur de ...'),
    ('an environmentalist', 'un écologiste'),
    ('an eco-warrior', 'un militant écologiste'),
    ('a tree-hugger', 'un écolo'),
    ('to pose a threat to', 'être une menace pour'),
    ('to jeopardize / to endanger', 'mettre en danger'),
    ('harmful', 'nuisible, nocif'),
    ('harmless', 'inoffensif, sans danger'),
    ('damage', 'dégâts'),
    ('biodiversity', 'la biodiversité'),
    ('habitat', "l'habitat"),
    ('a species', 'une espèce'),
    ('to become extinct', 'disparaître'),
    ('to fell, cut down trees', 'abattre des arbres'),
    ('deforestation', 'la déforestation'),
    ('logging', "l'exploitation du bois"),
    ('to reforest', 'reboiser'),
    ('rewilding', 'réensauvagement'),
    ('natural resources', 'les ressources naturelles'),
    ('scarcity', 'la rareté'),
    ('depletion', "l'épuisement (ressources)")
]

vocab_list3 = [
    ('first', "premièrement/ tout d'abord"),
    ('first and foremost', 'avant tout'),
    ('to begin with', 'pour commencer'),
    ('moreover', 'en outre'),
    ('furthermore', 'en outre, de plus'),
    ("what's more", 'qui plus est'),
    ('not to mention', 'sans parler de'),
    ('not only... but also', 'non seulement... mais aussi'),
    ('as long as', 'tant que'),
    ('whenever', 'chaque fois que'),
    ('thanks to', 'grâce à'),
    ('due to', 'en raison de'),
    ('for lack of', 'faute de'),
    ('by means of', 'au moyen de'),
    ('regarding', 'en ce qui concerne'),
    ('as far as', 'dans la mesure où'),
    ('since', 'puisque'),
    ('namely', 'à savoir'),
    ('for instance', 'par exemple'),
    ('thereby', 'par là même'),
    ('on the one hand', "d'une part"),
    ('on the other hand', "d'autre part"),
    ('given that', 'étant donné que'),
    ('granted that', 'en admettant que'),
    ('provided that', 'à condition que'),
    ('no matter', 'peu importe'),
    ('on the contrary', 'au contraire'),
    ('albeit', 'bien que, quoique'),
    ('unlike', 'à la différence de'),
    ('though, although', 'bien que'),
    ('despite, in spite of', 'malgré'),
    ('yet', 'cependant'),
    ('and yet', 'et pourtant'),
    ('however', 'cependant'),
    ('still', 'toutefois'),
    ('while', 'alors que'),
    ('whereas', 'tandis que'),
    ('unless', 'à moins que, sauf si'),
    ('nevertheless, nonetheless', 'néanmoins, toutefois'),
    ('obviously', 'de toute évidence'),
    ('similarly', 'de la même façon'),
    ('likewise', 'de même'),
    ('thus', 'ainsi'),
    ('consequently', 'en conséquence'),
    ('therefore', "donc, c'est pourquoi"),
    ('finally', 'finalement'),
    ('on the whole', "dans l'ensemble"),
    ('explain', 'expliquer'),
    ('mean', 'signifier, vouloir dire'),
    ('wonder if/whether', 'se demander si'),
    ('argue that', 'soutenir que'),
    ('assert, affirm', 'affirmer'),
    ('claim', 'prétendre'),
    ('note', 'constater, observer'),
    ('state', 'déclarer'),
    ('mention', 'mentionner'),
    ('stress that', "mettre l'accent sur"),
    ('emphasize, underline', 'souligner'),
    ('point out that', 'faire remarquer que'),
    ('recognize that', 'reconnaître que'),
    ('acknowledge sth', 'convenir de qch'),
    ('concede', 'concéder'),
    ('criticize', 'critiquer'),
    ('deny', 'nier'),
    ('highlight', 'mettre en avant'),
    ('shed light on', 'éclairer'),
    ('outline', 'expliquer (grandes lignes)'),
    ('contradict', 'contredire')
]

# Create a new deck with a unique ID
my_deck_id = 2099400160
my_deck = genanki.Deck(
  my_deck_id,
  'Spé::Anglais::Vocabulaire::9.1. Discussing issues'
)

# Add notes (cards) to the deck
for french, english in vocab_list3:
  note = genanki.Note(
    model=my_model,
    fields=[english, french]
  )
  my_deck.add_note(note)

# Save the deck to a file
genanki.Package(my_deck).write_to_file('C:/Users/alban/Downloads/vocabulaire_8.apkg')

print('Fichier vocabulaire.apkg généré avec succès.')